### PR TITLE
encourage people to tag version number in accordance with semver

### PR DESCRIPTION
**Pull request by stevengj**
(There seems to be persistent confusion about this in METADATA PRs.)

### CODE REVIEW

**Comment by tkelman** [comment]
We should mention dropping support for old versions of Julia counts as an API break. I've only been enforcing that as minor, but that's since most packages are still 0.x

**Comment by stevengj** [comment]
Ok.

**Comment by stevengj** [comment]
We should also consider having `PkgDev.tag(pkg)` print out an error message explaining major/minor/patch rather than defaulting to a patch increment.

**Comment by tkelman** [comment]
pedantic, but informative

**Pull request merged**
