### PR TITLE
Add deps/deps.jl to default .gitignore (issue #128)

### PR DESCRIPTION
**Pull request by phipsgabler**

### CODE REVIEW

**Comment by tkelman** [comment]
This has come up before, it's a BinDeps specific convention and doesn't necessarily apply to every julia package.

**Comment by phipsgabler** [comment]
OK... As I said in the issue, I don't actually know whether including this line is desirable in general. But I'd like the PkgDev default to agree with the GitHub default. 

Would you instead suggest removing it from GitHub's default? I haven't found any discussion about this in the older issues, but @ararslan in #128 seemed to support adding it here.

**Comment by ararslan** [comment]
Sure, it may not apply to every package, but I think it would be good to be generous with the default .gitignore.

**Comment by tkelman** [comment]
see https://github.com/JuliaLang/julia/pull/9541#issuecomment-68500922

**Comment by Nosferican** [comment]
I would suggest adding `.DS_Store` for Mac OS since it can't harm and would save Mac OS users an edit.

**Comment by ararslan** [comment]
`.DS_Store` is something that should go in a global gitignore file rather than every repo.

**Pull request closed without merging**
