### PR TITLE
Add Internet Systems Consortium License (ICL)

### PR DESCRIPTION
**Pull request by juliohm**
The license is equivalent to BSD 2-Clause and MIT licenses. It eliminates unnecessary language in the latter as discussed in the two links below:

- https://en.wikipedia.org/wiki/ISC_license
- https://github.com/juliohm/ImageQuilting.jl/blob/master/LICENSE (see GitHub header explanation)

I appreciate if you can merge it to PkgDev.jl.

### CODE REVIEW

**Comment by juliohm** [comment]
Any concern about adding this license? I see myself always creating a package with `Pkg.generate()` and manually changing the `LICENSE.md` to ISC. The fact that it is equivalent to MIT and has less boiler plate language makes it my to-go license for open source.

**Comment by ararslan** [comment]
Needs a mention in the README, otherwise looks good to me.

**Comment by juliohm** [comment]
Thank you @ararslan, added the mention to the README.

**Comment by ararslan** [comment]
Thanks!

**Pull request merged**
