### PR TITLE
GitHub module updates

### LINKED ISSUE #15: Provide a system name in a GitHub 2FA access token
Currently a GitHub 2FA token is generated with name - Julia Package Manager. If there are more then one system used for development, it is hard to distinguish where which token was generated.

screenshot from 2015-10-17 21 13 59

A possible solution is to provide a system name or an IP address of the system  where token was generated.

### PR DESCRIPTION
**Pull request by wildart**
Fixed #15 by adding host name to token label. Backported julia/#14849 - windows curl path discovery.

### CODE REVIEW

**Comment by tkelman** [comment]
This isn't the right long term fix for the windows issue, since command line git will be going away.

**Comment by wildart** [comment]
So whole windows path is rubbish. Where is `curl` location then?

**Comment by tkelman** [comment]
This will work temporarily, but it's not yet decided whether curl is going to be a bundled dependency on Windows. Writing a Windows-specific Powershell alternative would work without adding any new dependencies, since it's always present on all the versions of Windows that we support. There's a very simple API in Powershell for interacting with REST API's - nicer than curl IMO https://technet.microsoft.com/en-us/library/hh849971.aspx

**Comment by wildart** [comment]
I'm removed julia/#14849 backport.

**Comment by tkelman** [comment]
lgtm

**Pull request merged**
